# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: self-hosted
   
    steps:
     
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
         aws-region: us-east-1
        # role-to-assume: arn:aws:iam::779527285137:role/AWSdevopscerttaskrole
      - name: cluster credentials
        run: Cross_Acc_Role=$(aws sts assume-role --role-arn arn:aws:iam::779527285137:role/AWSdevopscerttaskrole --role-session-name AWSCLI-Session --profile default) export AWS_ACCESS_KEY_ID=$(echo $Cross_Acc_Role | jq -r .Credentials.AccessKeyId) export AWS_SECRET_ACCESS_KEY=$(echo $Cross_Acc_Role | jq -r .Credentials.SecretAccessKey) export AWS_SESSION_TOKEN=$(echo $Cross_Acc_Role | jq -r .Credentials.SessionToken)
    
      - name: cluster connetion
        run: aws eks update-kubeconfig --name cluster_project1 --region us-east-1

    # Steps represent a sequence of tasks that will be executed as part of the jo

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         role-to-assume: arn:aws:iam::779527285137:role/AWSdevopscerttaskrole
         aws-region: us-east-1
      - name: cluster mapping
        run: aws eks update-kubeconfig --name cluster_project1 --region us-east-1
      - name: Prometheus namespace
        run: kubectl create namespace prometheus
      - name: helm prometheus 
        run: helm install prometheus prometheus-community/prometheus --namespace prometheus --set alertmanager.persistentVolume.storageClass="gp2" --set server.persistentVolume.storageClass="gp2" --set server.service.type=LoadBalancer
      - name: namespace grafana
        run: kubectl create namespace grafana
      - name: helm grafana
        run: helm install grafana grafana/grafana --namespace grafana --set persistence.storageClassName="gp2" --set persistence.enabled=true --set adminPassword='secretpass' --values ~/monitoring/grafana/grafana.yaml --set service.type=LoadBalancer
